branch-defaults:
  main:
    environment: my-springboot-env
environment-defaults:
  my-springboot-env:
    branch: null
    repository: null
global:
  application_name: 21Logic
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
